// <auto-generated />
using System;
using Aula005.RazorPages.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aula005.RazorPages.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Aula005.RazorPages.Model.Aluno", b =>
                {
                    b.Property<int?>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlunoNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cursos")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInscricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.HasKey("AlunoId");

                    b.ToTable("Jogadores", (string)null);
                });

            modelBuilder.Entity("Aula005.RazorPages.Model.Curso", b =>
                {
                    b.Property<int?>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateInicio")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateTermino")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCurso")
                        .HasColumnType("TEXT");

                    b.HasKey("CursoId");

                    b.ToTable("Eventos", (string)null);
                });

            modelBuilder.Entity("CursoAluno", b =>
                {
                    b.Property<int>("CursoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlunoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CursoId", "AlunoId");

                    b.HasIndex("AlunoId");

                    b.ToTable("CursosEAlunos", (string)null);
                });

            modelBuilder.Entity("CursoAluno", b =>
                {
                    b.HasOne("Aula005.RazorPages.Model.Aluno", null)
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aula005.RazorPages.Model.Curso", null)
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
